# R Programming NPTEL Week 10

## 1. String substitution

In [1]:
y <- "Number of participants: 25"
sub("25", "30", y)
y <- "Mr. Singh is the smart one. Mr. Singh is funny, too."
sub("Mr. Singh", "Professor Jha", y)
gsub("Mr. Singh", "Professor Jha", y)

[1] "Number of participants: 30"

[1] "Professor Jha is the smart one. Mr. Singh is funny, too."

[1] "Professor Jha is the smart one. Professor Jha is funny, too."

## 2. Searching strings with grep

In [2]:
str <- c("R Course", "exercises", "include examples of R language")
grep("ex", str, value = TRUE)
grep("ex", str, value = FALSE)
str2 <- c("R Course", "exercises", "include examples of r language", "in R software.")
grep("R", str2, ignore.case = FALSE, value = TRUE)
grep("R", str2, ignore.case = TRUE, value = TRUE)
x <- "R course 24.07.2021"
y <- "Number of participants: 25"
grep("our", c(x, y))
grep("Num", c(x, y))

[1] "exercises"                      "include examples of R language"

[1] 2 3

[1] "R Course"       "in R software."

[1] "R Course"                       "exercises"
[3] "include examples of r language" "in R software."

[1] 1

[1] 2

## 3. Searching strings with grepl

In [3]:
str <- c("R Course", "exercises", "include examples of R language")
grepl("R", str)
grepl("ex", str)

[1]  TRUE FALSE  TRUE

[1] FALSE  TRUE  TRUE

## 4. Creating and inspecting data frames

In [4]:
students <- data.frame(
  Name = c("Asha", "Riya", "Neha", "Amit"),
  Age = c(21, 20, 22, 21),
  Marks = c(85, 92, 76, 88),
  Department = c("CMPN", "IT", "CMPN", "EXTC")
)
students
str(students)
colnames(students)
rownames(students)
summary(students)
is.numeric(students$Age)
is.factor(students$Department)

  Name Age Marks Department
1 Asha 21  85    CMPN
2 Riya 20  92    IT
3 Neha 22  76    CMPN
4 Amit 21  88    EXTC

'data.frame':	4 obs. of  4 variables:
 $ Name      : chr  "Asha" "Riya" "Neha" "Amit"
 $ Age       : num  21 20 22 21
 $ Marks     : num  85 92 76 88
 $ Department: chr  "CMPN" "IT" "CMPN" "EXTC"

[1] "Name"       "Age"        "Marks"      "Department"

[1] "1" "2" "3" "4"

        Name        Age            Marks           Department
 Length   :4   Min.   :20.00   Min.   :76.00   Length   :4
 N.unique :4   1st Qu.:20.75   1st Qu.:82.75   N.unique :3
 N.blank  :0   Median :21.00   Median :86.50   N.blank  :0
 Min.nchar:4   Mean   :21.00   Mean   :85.25   Min.nchar:2
 Max.nchar:4   3rd Qu.:21.25   3rd Qu.:89.00   Max.nchar:4
               Max.   :22.00   Max.   :92.00

[1] TRUE

[1] FALSE

## 5. Row names and column access

In [5]:
painters <- data.frame(
  Composition = c(10, 15, 8, 12, 0),
  Drawing = c(8, 16, 13, 16, 15),
  Colour = c(16, 4, 16, 9, 8),
  Expression = c(3, 14, 7, 8, 0),
  School = factor(c("A", "A", "A", "A", "A")),
  row.names = c("Da Udine", "Da Vinci", "Del Piombo", "Del Sarto", "Fr. Penni")
)
painters
painters$Drawing
painters["School"]
rownames(painters)
colnames(painters)
summary(painters)
summary(painters$School)

           Composition Drawing Colour Expression School
Da Udine   10           8      16      3         A
Da Vinci   15          16       4     14         A
Del Piombo  8          13      16      7         A
Del Sarto  12          16       9      8         A
Fr. Penni   0          15       8      0         A

[1]  8 16 13 16 15

           School
Da Udine   A
Da Vinci   A
Del Piombo A
Del Sarto  A
Fr. Penni  A

[1] "Da Udine"   "Da Vinci"   "Del Piombo" "Del Sarto"  "Fr. Penni"

[1] "Composition" "Drawing"     "Colour"      "Expression"  "School"

  Composition    Drawing         Colour       Expression   School
 Min.   : 0   Min.   : 8.0   Min.   : 4.0   Min.   : 0.0   A:5
 1st Qu.: 8   1st Qu.:13.0   1st Qu.: 8.0   1st Qu.: 3.0
 Median :10   Median :15.0   Median : 9.0   Median : 7.0
 Mean   : 9   Mean   :13.6   Mean   :10.6   Mean   : 6.4
 3rd Qu.:12   3rd Qu.:16.0   3rd Qu.:16.0   3rd Qu.: 8.0
 Max.   :15   Max.   :16.0   Max.   :16.0   Max.   :14.0

A
5

## 6. Subsetting data frames

In [6]:
subset(painters, School == "A")
subset(painters, Composition <= 10)
subset(painters, School == "A", select = c(-3, -5))
painters[painters$Composition <= 10, ]
painters[, c("Composition", "Drawing", "Expression")]

           Composition Drawing Colour Expression School
Da Udine   10           8      16      3         A
Da Vinci   15          16       4     14         A
Del Piombo  8          13      16      7         A
Del Sarto  12          16       9      8         A
Fr. Penni   0          15       8      0         A

           Composition Drawing Colour Expression School
Da Udine   10           8      16     3          A
Del Piombo  8          13      16     7          A
Fr. Penni   0          15       8     0          A

           Composition Drawing Expression
Da Udine   10           8       3
Da Vinci   15          16      14
Del Piombo  8          13       7
Del Sarto  12          16       8
Fr. Penni   0          15       0

           Composition Drawing Colour Expression School
Da Udine   10           8      16     3          A
Del Piombo  8          13      16     7          A
Fr. Penni   0          15       8     0          A

           Composition Drawing Expression
Da Udine   10           8       3
Da Vinci   15          16      14
Del Piombo  8          13       7
Del Sarto  12          16       8
Fr. Penni   0          15       0

## 7. Attaching a data frame

In [7]:
attach(painters)
Drawing
School
detach(painters)

[1]  8 16 13 16 15

[1] A A A A A
Levels: A

## 8. Splitting data frames

In [8]:
split(painters, painters$School)

$A
           Composition Drawing Colour Expression School
Da Udine            10       8     16          3      A
Da Vinci            15      16      4         14      A
Del Piombo           8      13     16          7      A
Del Sarto           12      16      9          8      A
Fr. Penni            0      15      8          0      A

## 9. Combining data frames with cbind

In [9]:
df1 <- data.frame(
  state = c("UP", "MP", "AP", "JK"),
  popnsize = c(1000, 2000, 3000, 4000)
)
df2 <- data.frame(
  state = c("UP", "MP", "AP", "JK"),
  samplesize = c(100, 200, 300, 400),
  surveycompleted = c("Yes", "No", "Yes", "No")
)
cbind(df1, df2)

  state popnsize state samplesize surveycompleted
1 UP    1000     UP    100        Yes
2 MP    2000     MP    200        No
3 AP    3000     AP    300        Yes
4 JK    4000     JK    400        No

## 10. Merging data frames

In [10]:
merge(df1, df2, by = "state")

  state popnsize samplesize surveycompleted
1 AP    3000     300        Yes
2 JK    4000     400        No
3 MP    2000     200        No
4 UP    1000     100        Yes

## 11. Combining data frames with rbind

In [11]:
df11 <- data.frame(
  state = c("UP", "MP", "AP", "JK"),
  popnsize = c(1000, 2000, 3000, 4000)
)
df22 <- data.frame(
  state = c("Bihar", "Delhi", "Punjab"),
  popnsize = c(100, 200, 300)
)
rbind(df11, df22)

  state  popnsize
1 UP     1000
2 MP     2000
3 AP     3000
4 JK     4000
5 Bihar   100
6 Delhi   200
7 Punjab  300

## 12. Practice

In [12]:
products <- data.frame(
  Product = c("Laptop", "Phone", "Tablet", "Laptop"),
  Price = c(55000, 25000, 18000, 60000),
  Category = c("Electronics", "Electronics", "Electronics", "Electronics")
)
subset(products, Price > 20000)
grep("top", c("laptop", "desktop", "top seller"), value = TRUE)
gsub("Electronics", "Tech", products$Category)

  Product Price Category
1 Laptop  55000 Electronics
2 Phone   25000 Electronics
4 Laptop  60000 Electronics

[1] "laptop"     "desktop"    "top seller"

[1] "Tech" "Tech" "Tech" "Tech"